//DELETE http://localhost:3001/api/persons/3 HTTP/1.1
//Content-Type: application/json

//POST http://localhost:3001/api/persons/
//Content-Type: application/json

//{
//    "name": "Anni Cee",
//    "number": "045-45547522"
//}

// Render-appin testaus:

//DELETE https://puhelinluettelo-riij.onrender.com/api/persons/3 HTTP/1.1

//POST https://puhelinluettelo-riij.onrender.com/api/persons/
//Content-Type: application/json

//{
//    "name": "Anni Cee",
//    "number": "045-45547522"
//}